### ISSUE TITLE
ModuleNotFoundError: No module named 'openai'

### ISSUE THREAD

**Issue by ihazem** [openai/openai-quickstart-python#40]
In following the instructions [here](https://platform.openai.com/docs/quickstart/build-your-application), I got the below error. It was defaulting to my anaconda flask lib. The instructions should probably point the user to use flask in the venv. Suggestion to change the command in the doc to be `./venv/bin/flask run`, as that worked for me.

```
(venv) /Users/<username>/Documents/Development/openai-quickstart-python % flask run
 * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: While importing "app", an ImportError was raised:

Traceback (most recent call last):
  File "/Users/<username>/opt/anaconda3/lib/python3.8/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/Users/<username>/Documents/Development/openai-quickstart-python/app.py", line 3, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
```

**Comment by francomariani94** [comment]
Try with: `python -m flask run`

**Comment by logankilpatrick** [comment]
Hey! Make sure you have the latest SDK version from: https://github.com/openai/openai-python
