### ISSUE TITLE
openai.error.RateLimitError

### ISSUE THREAD

**Issue by 0xVelo** [openai/openai-quickstart-python#52]
openai.error.RateLimitError
openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.

Traceback (most recent call last)
File "C:\openai-quickstart-python\venv\Lib\site-packages\flask\app.py", line 2091, in __call__
return self.wsgi_app(environ, start_response)
File "C:\openai-quickstart-python\venv\Lib\site-packages\flask\app.py", line 2076, in wsgi_app
response = self.handle_exception(e)
File "C:\openai-quickstart-python\venv\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "C:\openai-quickstart-python\venv\Lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "C:\openai-quickstart-python\venv\Lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "C:\openai-quickstart-python\venv\Lib\site-packages\flask\app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "C:\openai-quickstart-python\app.py", line 14, in index
response = openai.Completion.create(
File "C:\openai-quickstart-python\venv\Lib\site-packages\openai\api_resources\completion.py", line 31, in create
return super().create(*args, **kwargs)
File "C:\openai-quickstart-python\venv\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 100, in create
response, _, api_key = requestor.request(
File "C:\openai-quickstart-python\venv\Lib\site-packages\openai\api_requestor.py", line 122, in request
resp, got_stream = self._interpret_response(result, stream)
File "C:\openai-quickstart-python\venv\Lib\site-packages\openai\api_requestor.py", line 329, in _interpret_response
self._interpret_response_line(
File "C:\openai-quickstart-python\venv\Lib\site-packages\openai\api_requestor.py", line 362, in _interpret_response_line
raise self.handle_error_response(
openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.

I have a paid API account and I have 120$ credit monthly plus 5$ grant. I have only used less than 0.01$ of my total credits and still got the above error, someone can help?

**Comment by 202030481266** [comment]
I also have the same problem.

**Comment by logankilpatrick** [comment]
See here for details: https://platform.openai.com/docs/guides/rate-limits/rate-limits
